[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
agent_pay_vault = "CvE7xMfwbpMmCz9Pvt6RsG9tHxNUpbuG5KwyGuFHSxCk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"
